
"use client";

import { useState } from 'react';
import { Bot, Loader2, Send, User, ShieldAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Textarea } from '@/components/ui/textarea';
import { useApi } from '@/hooks/useApi';
import { useAuth } from '@/hooks/useAuth';
import { cn } from '@/lib/utils';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import Image from 'next/image';

interface Message {
  sender: 'USER' | 'AI';
  text: string;
}

const isImageDataUri = (text: string) => text.startsWith('data:image/');

export default function SuperadminKaiPage() {
  const { role } = useAuth();
  const [messages, setMessages] = useState<Message[]>([]);
  const [prompt, setPrompt] = useState('');

  const askAuthenticatedKaiMutation = useApi<{ reply: string }>('askAuthenticatedKai');

  const handleSend = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim() || askAuthenticatedKaiMutation.isPending) return;

    const userMessage: Message = { sender: 'USER', text: prompt };
    const conversationHistory = [...messages, userMessage];

    setMessages(conversationHistory);
    setPrompt('');

    const response = await askAuthenticatedKaiMutation.mutateAsync({ 
      query: prompt, 
      conversationHistory: messages // Send previous messages for context
    });

    if (response) {
      setMessages(prev => [...prev, { sender: 'AI', text: response.reply }]);
    }
  };

  if (role !== 'superadmin' && role !== 'admin') {
    return (
      <div className="flex items-center justify-center h-full">
        <Alert variant="destructive" className="max-w-md">
          <Bot className="h-4 w-4" />
          <AlertTitle>Access Denied</AlertTitle>
          <AlertDescription>
            This interface is restricted to Administrators only.
          </AlertDescription>
        </Alert>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-[calc(100vh-100px)]">
        <CardHeader className="p-0 pb-4">
            <CardTitle className="font-headline text-3xl font-bold tracking-tight">Kai Admin Console</CardTitle>
            <CardDescription>Directly interact with the Kai AI assistant with elevated privileges and context.</CardDescription>
        </CardHeader>

        <Card className="flex-1 flex flex-col">
            <CardContent className="flex-1 p-4 overflow-hidden">
                <ScrollArea className="h-full pr-4">
                    <div className="space-y-4">
                        {messages.length === 0 && (
                            <Alert>
                                <ShieldAlert className="h-4 w-4" />
                                <AlertTitle>Admin Capabilities</AlertTitle>
                                <AlertDescription>
                                    As an admin, you can ask Kai to perform privileged actions. Try prompts like:
                                    <ul className="list-disc pl-5 mt-2 text-xs">
                                        <li>"Suspend user [user_id]"</li>
                                        <li>"Generate an image of a secure vault"</li>
                                    </ul>
                                </AlertDescription>
                            </Alert>
                        )}
                        {messages.map((msg, index) => (
                             <div key={index} className={cn("flex items-start gap-3", { 'justify-end flex-row-reverse': msg.sender === 'USER' })}>
                                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-secondary">
                                    {msg.sender === 'AI' ? <Bot className="h-5 w-5 text-primary"/> : <User className="h-5 w-5 text-foreground"/>}
                                </div>
                                <div className={cn("max-w-[80%] rounded-lg px-3 py-2 text-sm break-words", 
                                    msg.sender === 'AI' ? 'bg-muted text-foreground' : 'bg-primary text-primary-foreground'
                                )}>
                                    {isImageDataUri(msg.text) ? (
                                        <Image src={msg.text} alt="Generated by AI" width={256} height={256} className="rounded-md" data-ai-hint="illustration design"/>
                                    ) : (
                                        msg.text
                                    )}
                                </div>
                            </div>
                        ))}
                         {askAuthenticatedKaiMutation.isPending && (
                            <div className="flex items-start gap-3">
                                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-secondary">
                                    <Bot className="h-5 w-5 text-primary"/>
                                </div>
                                <div className="bg-muted rounded-lg px-3 py-2 flex items-center">
                                    <Loader2 className="h-5 w-5 animate-spin text-muted-foreground"/>
                                </div>
                            </div>
                        )}
                    </div>
                </ScrollArea>
            </CardContent>
            <CardContent className="border-t p-4">
                 <form onSubmit={handleSend} className="space-y-4">
                     <div className="space-y-2">
                        <Label htmlFor="prompt">Your Prompt</Label>
                        <div className="flex items-center gap-2">
                           <Textarea 
                                id="prompt" 
                                value={prompt} 
                                onChange={(e) => setPrompt(e.target.value)}
                                placeholder="Ask Kai to perform an action, query data, or generate an image..."
                                rows={2}
                                onKeyDown={(e) => {
                                    if (e.key === 'Enter' && !e.shiftKey) {
                                        e.preventDefault();
                                        handleSend(e);
                                    }
                                }}
                            />
                            <Button type="submit" size="icon" disabled={askAuthenticatedKaiMutation.isPending || !prompt}>
                                <Send />
                                <span className="sr-only">Send</span>
                            </Button>
                        </div>
                     </div>
                </form>
            </CardContent>
        </Card>
    </div>
  );
}
